---
    version: 3
    
    build_arg_defaults:
      ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'
    
    dependencies:
      ansible_core:
        package_pip: ansible-core
      ansible_runner:
        package_pip: ansible-runner
      galaxy: requirements.yml
      python: requirements.txt
      exclude:
        python:
          - docker
        system:
          - python3-Cython
    
    images:
      base_image:
        name: registry.redhat.io/ubi9/ubi:latest
        # Other available base images:
        #   - quay.io/rockylinux/rockylinux:9
        #   - quay.io/centos/centos:stream9
        #   - registry.fedoraproject.org/fedora:38
        #   - registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest
        #     (needs an account)
    
    additional_build_files:
        - src: ansible.cfg
          dest: configs
    
    additional_build_steps:
      prepend_base:
        - RUN echo This is a prepend base command!
        # Enable Non-default stream before packages provided by it can be installed. (optional)
        # - RUN $PKGMGR module enable postgresql:15 -y
        # - RUN $PKGMGR install -y postgresql
      prepend_galaxy:
        - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    
      prepend_final: |
        RUN whoami
        RUN cat /etc/os-release
      append_final:
        - RUN echo This is a post-install command!
        - RUN ls -la /etc
    